первое ревью
kseniaGabbasova/java-filmorate pull request #3
Opened 2022-07-18 01:28 UTC by kseniaGabbasova

2022-07-18 11:14 UTC, kukolev requested changes

2022-07-18 11:14 UTC, kukolev commented on src/main/java/com/example/filmorate/service/FilmService.java
> +    FilmStorage filmStorage;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-07-18 11:14 UTC, kukolev commented on src/main/java/com/example/filmorate/service/UserService.java
> +    UserStorage userStorage;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-07-18 11:14 UTC, kukolev commented on src/main/java/com/example/filmorate/storage/InMemoryFilmStorage.java
> +    UserStorage userStorage;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-07-18 11:14 UTC, kukolev commented on src/main/java/com/example/filmorate/storage/InMemoryFilmStorage.java
> +        log.info("Фильм добавлен");
При логировании лучше добавлять информацию о текущих значениях параметров, чтобы при анализе было понятно о чем идет речь. Здесь будет полезно добавить значение переменной film.

2022-07-18 11:14 UTC, kukolev commented on src/main/java/com/example/filmorate/service/FilmService.java
> +            return null;
По моему здесь и в подобных методах лучше бросать исключение. Тогда контроллер можно будет сделать проще , без проверок на null.

2022-07-20 01:55 UTC, kseniaGabbasova commented
второе ревью

2022-07-20 07:09 UTC, kukolev requested changes

2022-07-20 07:09 UTC, kukolev commented on src/main/java/com/example/filmorate/storage/InMemoryFilmStorage.java
> +            log.info("Добавлен фильм: " + film);
При логировании лучше использовать возможности библиотеки и пользоваться плейсхолдерами `{}` вместо конкатенации строк. Лучше так: `log.warn("Some warning text for {}", val)` вместо `log.warn("Some warning text for " + val)`. Так код смотрится проще и не происходит лишняя конкатенация строк, если лог не будет напечатан.

Нужно поправить здесь и ниже.

2022-07-20 07:09 UTC, kukolev commented on src/main/java/com/example/filmorate/controllers/FilmController.java
>      @GetMapping("/films/popular")
Ниже в @RequestParam можно указать значение по умолчанию = "10". Тогда не нужна будет проверка на null. Так код будет проще и привычней.

2022-07-20 21:20 UTC, kseniaGabbasova commented
третье ревью

2022-07-20 21:39 UTC, kukolev approved these changes

2022-07-22 00:22 UTC, merged